
module.exports = {
  usageData: [
    { label: 'Customer', value: 'Customer' },
    { label: 'TransactionDate', value: 'TransactionDate' },
    { label: 'TransactionStartTime', value: 'TransactionStartTime' },
    { label: 'TransactionEndTime', value: 'TransactionEndTime' },
    { label: 'Location', value: 'Location' },
    { label: 'Thing', value: 'Thing' },
    { label: 'UserType', value: 'UserType' },
    { label: 'JobDeliveryMethod', value: 'Print.JobDeliveryMethod' },
    { label: 'PrintJobSubmitted', value: 'Print.PrintJobSubmitted' },
    { label: 'Device', value: 'Print.Device' },
    { label: 'TotalCost', value: 'Print.TotalCost' },
    { label: 'GrayscaleCost', value: 'Print.GrayscaleCost' },
    { label: 'ColorCost', value: 'Print.ColorCost' },
    { label: 'TotalPages', value: 'Print.TotalPages' },
    { label: 'GrayscalePages', value: 'Print.GrayscalePages' },
    { label: 'ColorPages', value: 'Print.ColorPages' },
    { label: 'Copies', value: 'Print.Copies' },
    { label: 'PaperSize', value: 'Print.PaperSize' },
    { label: 'DocumentSize', value: 'Print.DocumentSize' },
    { label: 'Duplex', value: 'Print.Duplex' },
    { label: 'ColorType', value: 'Print.ColorType' },
    { label: 'JobPrinted', value: 'Print.JobPrinted' },
    { label: 'JobPrintedBy', value: 'Print.JobPrintedBy' },
    { label: 'JobPrintedFrom', value: 'Print.JobPrintedFrom' },
    { label: 'PrintCancelled', value: 'Print.PrintCancelled' },
    { label: 'ReasonCancelled', value: 'ReasonCancelled' },
    { label: 'JobType', value: 'Print.JobType' },
    { label: 'ReleaseCode', value: 'Print.ReleaseCode' },
    { label: 'PaymentType', value: 'Print.PaymentType' },
    { label: 'DocumentName', value: 'Print.DocumentName' },
    { label: 'DocumentType', value: 'Print.DocumentType' },
    { label: 'Orientation', value: 'Print.Orientation' },
    { label: 'Staple', value: 'Print.Staple' },
    { label: 'BillingAccountId', value: 'BillingAccountId' },
    { label: 'BillingAccountName', value: 'BillingAccountName' },
    { label: 'CurrencyCode', value: 'CurrencyCode' }
  ]
}