module.exports = {
  usages: require('./usages'),
  customers: require('./customers'),
  customizations: require('./customizations'),
  customizationTexts: require('./customizationText'),
  locations: require('./locations'),
  profiles: require('./profiles'),
  groups: require('./groups'),
  devices: require('./devices'),
  users: require('./users'),
  payment: require('./payment'),
  jobLists: require('./jobList'),
  validators: require('./validators'),
  things: require('./things'),
  dropdowns: require('./dropdowns'),
  permissions: require('./permissions'),
  roles: require('./roles'),
  licenses: require('./licensing'),
  customPermissions: require('./customPermissions'),
  publicUploads: require('./publicUploads'),
  partners: require('./partners'),
  authProviders: require('./authProviders'),
  auditLogs: require('./auditLogs'),
  versions: require('./versions'),
  faxes: require('./faxes'),
  accounts: require('./accounts'),
  thirdPartySoftware: require('./thirdPartySoftware')
}
