module.exports = {
  bucketName: process.env.S3BucketTenantUploads || 'cloud-eprintitsaas-pri-dev',
  roleArn: process.env.roleName || 'local-sts-credentialTestingRole',
  senderEmail: process.env.senderEmail || 'DoNotReply@eprintitsaas.org',
  region: process.env.region || 'us-east-1',
  primaryRegion: process.env.region === 'us-east-1'? 'us-east-1' : 'us-west-2' ,
  Stage: process.env.Stage ? process.env.Stage: 'dev',
  secondaryRegion:  process.env.region === 'us-east-1'? 'us-west-2' : 'us-east-1' ,
  awsAccountNumber: process.env.awsAccountNumber || '377667345683',
  roleName: process.env.roleName || 'local-sts-credentialTestingRole',
  domainName: process.env.domainName || 'eprintitsaas.org',
  localDatabase: process.env.dbName || 'saas-dev',
  MongoDB: process.env.mongoDBConnection || 'main.uh6ww',
  server: process.env.environment,
  secretEncryptionKeys: process.env.secretEncryptionKeys || 'tbs-ppl-encryption111111',
  secretEncryptionKeysIoT: process.env.secretEncryptionKeys || 'tbs-ppl-encryption',
  algorithmName: process.env.algorithmName || 'aes256',
  algorithmNameInt: process.env.algorithmNameInt || 'aes-192-cbc',
  ivValue: process.env.algorithmNameInt || 'E-PRINT-IT-SAAS1',
}
