const permissionMapping = {
  query: {
    GetUsages: ["Transactions", "Usage"],
    Dashboard: ["Analytics"],
    UserPortalDashboard: ["Details"],
    CsvReport: ["CSV_reports"],
    GetCustomers: [
      "Print_Release",
      "Users",
      "Identity_Provider",
      "Profiles",
      "Payment_List",
      "License",
      "Groups",
      "Roles",
      "Generate_API_Key",
      "Terms_of_Use",
      "Custom_Text",
      "Mobile_Configurations",
      "Print_Release",
      "Joblist_Settings",
      "Thing",
      "Devices",
      "Locations",
      "CSV_reports",
      "Kiosk_Transaction_Reports",
      "Executive_reports",
      "Printer_reports",
      "Add_Value_Reports",
      "Transaction_Report_Payment",
      "License_Report",
      "Customers",
      "Audit_Logs",
      "Upload_Page",
      "Add_Proton",
      "Update_Proton",
      "Add_Account_Sync",
      "Update_Account_Sync",
      "Add_Email",
      "Update_Email",
      "Add_Handwrite_Recognition",
      "Update_Handwrite_Recognition",
      "Add_Restore_Pictures",
      "Update_Restore_Pictures",
      "Add_Illiad",
      "Update_Illiad",
      "Add_Smartphone",
      "Update_Smartphone",
      "Add_FTP",
      "Update_FTP",
      "Add_Abby",
      "Update_Abby",
      "Add_Text_Translation",
      "Update_Text_Translation",
      "Add_Fax_Integration",
      "Update_Fax_Integration",
      "Add_Network",
      "Update_Network",
      "Add_Audio",
      "Update_Audio",
    ],
    GetCustomer: [
      "Customers",
      "Users",
      "Profiles",
      "Payment_List",
      "License",
      "Groups",
    ],
    GetCustomization: [
      "Customers",
      "Users",
      "Profiles",
      "Payment_List",
      "License",
      "Groups",
      "Roles",
    ],
    UploadLogo: ["Customers", "Upload_Page"],
    GetLocations: [
      "Thing",
      "Add_Thing",
      "Update_Thing",
      "Devices",
      "Add_Device",
      "Update_Device",
      "Mobile_Configurations",
      "CSV_reports",
      "Kiosk_Transaction_Reports",
      "Executive_reports",
      "Printer_reports",
      "Locations",
      "Joblist_Settings",
      "Customers",
      "Add_Customer",
      "Add_Location",
      "Update_Location",
      "Profiles",
      "Print_Release"
    ],
    GetLocation: ["Locations", "Add_Customer"],
    GetGroups: [
      "Customers",
      "Users",
      "Groups",
      "Profiles",
      "Identity_Provider",
      "Add_Group", 
      "Update_Group"
    ],
    GetGroup: ["Groups", "Print_Release"],
    GetThings: ["Thing", "Joblist_Settings", "Customers"],
    GetThing: ["Thing"],
    GenerateActivationCode: ["Thing"],
    GetDevices: ["Groups", "Thing", "Devices", "Print_Release", "Usage"],
    GetDevice: ["Devices"],
    GetUsers: ["Users"],
    UserBalance: ["Add_Value", "Print_Release"],
    FindDataExisting: [
      "Add_User",
      "Add_Profile",
      "Add_Location",
      "Add_Customer",
    ],
    GetCustomizationText: [
      "Terms_of_Use",
      "Add_Value",
      "Print_Release",
      "Custom_Text",
      "Customers",
      "Mobile_Configurations",
      "CSV_reports",
      "Kiosk_Transaction_Reports",
      "Executive_reports",
      "Printer_reports",
      "Upload_Page",
    ],
    GetLicenses: ["License"],
    GetLicense: [
      "License",
      "Profiles",
      "Customers",
      "Groups",
      "Payment_List",
      "Identity_Provider",
      "Users",
    ],
    LicenseExpiringCustomers: ["License_Report"],
    GetParentChildPermission: ["Roles"],
    GetRoles: ["Groups", "Roles", "Users", "Customers", "Add_Customer"],
    GetRole: ["Roles"],
    GetJobLists: ["Prices", "Devices", "Joblist_Settings", "Print_Release"],
    GetPaymentConfigurations: ["Payment_List", "Add_Value"],
    GetBrainTreeClientToken: ["Add_Value"],
    GetStripeRedirectUrl: ["Add_Value"],
    GetAuthorizeNetClientToken: ["Add_Value"],
    GetEghlHash: ["Add_Value"],
    GetPay88Signature: ["Add_Value"],
    GetHeartlandHash: ["Add_Value"],
    GetXenditInvoiceURL: ["Add_Value"],
    GetMonerisTicket: ["Add_Value"],
    GetProfiles: ["Profiles"],
    GetProfile: ["Profiles"],
    GetDropdowns: [
      "Terms_of_Use",
      "License",
      "Profiles",
      "Software_Update",
      "Thing",
      "Devices",
      "ThirdPartySoftwareType"
    ],
    GetCustomPermissions: ["Roles"],
    GetPublicUploads: ["Print_Release"],
    GetPublicUpload: ["Print_Release"],
    GetPartners: ["Generate_API_Key"],
    GetPartnerById: ["Generate_API_Key"],
    GetAuthProviders: ["Thing", "Identity_Provider", "Profiles"],
    GetAuthProvider: ["Identity_Provider"],
    BuildIdPMetadata: ["Identity_Provider"],
    GetVersions: ["Software_Update"],
    GetVersion: ["Software_Update"],
    GetPaperSizes: ["Joblist_Settings"],
    GetAuditLogs: ["Audit_Logs"],
    LocationQuery_DeviceAndThingType_DeviceQuery: [
      "Devices",
      "Add_Device",
      "Update_Device",
    ],
    LocationQuery_DeviceAndThingType: [
      "Devices",
      "Thing",
      "Add_Thing",
      "Update_Thing",
      "Add_Device",
      "Update_Device",
    ],
    LocationQuery_DeviceAndThingType_ThingQuery: [
      "Thing",
      "Add_Thing",
      "Update_Thing",
    ],
    LocationQuery: [
      "Thing",
      "Add_Thing",
      "Update_Thing",
      "Devices",
      "Add_Device",
      "Update_Device",
      "Mobile_Configurations",
      "CSV_reports",
      "Kiosk_Transaction_Reports",
      "Executive_reports",
      "Printer_reports",
      "Locations",
      "Joblist_Settings",
      "Customers",
      "Add_Customer",
      "Add_Location",
      "Update_Location",
      "Profiles",
      "Print_Release"
    ], // GetLocations
    ThingQuery: ["Thing", "Joblist_Settings", "Customers"], // GetThings
    DeviceQuery: ["Groups", "Thing", "Devices", "Print_Release", "Usage"], // GetDevices
    GetAccountSync: ["Read_Account_Sync"],
    GetProton: ["Read_Proton"],
    GetAccounts: ["Read_Account"], //GetAccounts
    GetAccount: ["Read_Account"], //GetAccount
    GetBillingServices: ["Read_Proton", "Add_Proton", "Update_Proton", "Delete_Proton"],
    GetThirdPartySoftware: [
      "Third_Party",
      "Read_Proton",
      "Read_Account_Sync",
      "Read_Email",
      "Read_Handwrite_Recognition",
      "Read_Restore_Pictures",
      "Read_Illiad",
      "Read_Smartphone",
      "Read_FTP",
      "Read_Abby",
      "Read_Fax_Integration",
      "Read_Text_Translation",
      "Read_Network",
      "Read_Audio"
    ],
    GetSubCustomers: ["Customers"],
    GetEmail: ["Read_Email"],
    GetHandWriteRecognition: ["Read_Handwrite_Recognition"],
    GetRestorePictures: ["Read_Restore_Pictures"],
    GetIlliad: ["Read_Illiad"],
    GetSmartphone: ["Read_Smartphone"],
    GetFTP: ["Read_FTP"],
    GetThirdPartySupportedLanguages: ["Add_Abby", "Update_Abby"],
    GetAbby: ["Read_Abby"],
    GetTextTranslation: ["Read_Text_Translation"],
    GetFaxIntegration: ["Read_Fax_Integration"],
    GetNetwork: ["Read_Network"],
    GetAudio: ["Read_Audio"],
  },
  mutation: {
    UpdateCustomer: ["Update_Customer"],
    CustomerDeleted: ["Delete_Customer"],
    CustomerStatus: ["Update_Customer"],
    OnboardCustomer: ["Add_Customer"],
    UpdateCustomization: ["Update_Customer"],
    CustomizationStatus: ["Update_Customer"],
    AddLocation: ["Add_Location"],
    UpdateLocation: ["Update_Location"],
    LocationDeleted: ["Delete_Location"],
    LocationStatus: ["Update_Location"],
    AddGroup: ["Add_Group"],
    VerifyEasyBookingRules: ["Update_Identity_Provider", "Identity_Provider"],
    UpdateGroup: ["Update_Group"],
    GroupDeleted: ["Delete_Group"],
    GroupStatus: ["Update_Group"],
    UpdateEasyBookingGroupPriorities: ["Add_Group", "Update_Group"],
    AddProton: ["Add_Proton"],
    UpdateProton: ["Update_Proton"],
    ProtonDeleted: ["Delete_Proton"],
    ProtonStatus: ["Update_Proton"],
    AddEmail: ["Add_Email"],
    UpdateEmail: ["Update_Email"],
    EmailDeleted: ["Delete_Email"],
    EmailStatus: ["Update_Email"],
    AddSmartphone: ["Add_Smartphone"],
    UpdateSmartphone: ["Update_Smartphone"],
    SmartphoneDeleted: ["Delete_Smartphone"],
    SmartphoneStatus: ["Update_Smartphone"],
    ResetQuotaBalance: ["Reset_Quota_Balance"],
    AddThing: ["Add_Thing"],
    UpdateThing: ["Update_Thing"],
    ThingDeleted: ["Delete_Thing"],
    ThingStatus: ["Update_Thing"],
    AddDevice: ["Add_Device"],
    UpdateDevice: ["Update_Device"],
    DeviceStatus: ["Update_Device"],
    DeviceDeleted: ["Delete_Device"],
    UploadMultipleFiles: ["Print_Release"],
    UploadMultipleFilesV2: ["Print_Release"],
    AddUser: ["Add_User"],
    UpdateUser: ["Update_User"],
    UpdateUserBalance: ["Update_Quota_Balance", "Update_Debit_Balance"],
    UpdateUserV2: ["Update_User"],
    AdminChangePassword: ["Update_User"],
    UserDeleted: ["Delete_User"],
    UpdateCustomizationText: [
      "Update_Customer",
      "Update_Upload_Page",
      "Terms_of_use",
      "Update_Text",
      "Edit_Mobile_Configuration",
    ],
    GenerateEmail: ["Update_Customer"],
    UpdateLicense: ["Update_License"],
    LicenseStatus: ["Update_License"],
    AddRole: ["Add_Role", "Clone_Role"],
    UpdateRole: ["Update_Role"],
    RoleDeleted: ["Delete_Role"],
    RoleStatus: ["Update_Role"],
    UpdateJobList: ["Update_Joblist"],
    JobListStatus: ["Update_Joblist"],
    AddPaymentConfiguration: ["Add_Payment"],
    UpdatePaymentConfiguration: ["Edit_Payment"],
    PaymentConfigurationDeleted: ["Delete_Payment"],
    PaymentConfigurationStatus: ["Edit_Payment"],
    AddProfile: ["Add_Profile"],
    UpdateProfile: ["Update Profile"],
    ProfileDeleted: ["Delete_Profile"],
    ProfileStatus: ["Update Profile"],
    UpdatePublicUpload: ["Add_Group", "Update_Group", "Print_Release", "Re-Print"],
    AddPartner: ["Generate_API_Key"],
    PartnerDeleted: ["Generate_API_Key"],
    PartnerStatus: ["Generate_API_Key"],
    AddAuthProvider: ["Add_Identity_Provider"],
    UpdateAuthProvider: ["Update_Identity_Provider"],
    AuthProviderDeleted: ["Delete_Identity_Provider"],
    AuthProviderStatus: ["Update_Identity_Provider"],
    AddVersion: ["Add_Software_Update"],
    UpdateVersion: ["Update_Software_Update"],
    VersionDeleted: ["Delete_Software_Update"],
    UploadVersion: ["Add_Software_Update", "Update_Software_Update"],
    UploadVersionV2: ["Add_Software_Update", "Update_Software_Update"],
    ConfirmFileUploadV2: ["Print_Release"],
    RequestChangePassword: ["Update_User"],
    AddAccountSync: ["Add_Account_Sync"],
    UpdateAccountSync: ["Update_Account_Sync"],
    DeleteAccountSync: ["Delete_Account_Sync"],
    AccountSyncStatus: ["Update_Account_Sync"],
    AddAccount: ["Add_Account"],
    UpdateAccount: ["Update_Account"],
    DeleteAccount: ["Delete_Account"],
    UpdateAccountStatus: ["Update_Account"],
    AddHandWriteRecognition: ["Add_Handwrite_Recognition"],
    UpdateHandWriteRecognition: ["Update_Handwrite_Recognition"],
    DeleteHandWriteRecognition: ["Delete_Handwrite_Recognition"],
    UpdateHandWriteRecognitionStatus: ["Update_Handwrite_Recognition"],
    AddRestorePictures: ["Add_Restore_Pictures"],
    UpdateRestorePictures: ["Update_Restore_Pictures"],
    DeleteRestorePictures: ["Delete_Restore_Pictures"],
    UpdateRestorePicturesStatus: ["Update_Restore_Pictures"],
    AddIlliad: ["Add_Illiad"],
    UpdateIlliad: ["Update_Illiad"],
    DeleteIlliad: ["Delete_Illiad"],
    UpdateIlliadStatus: ["Update_Illiad"],
    AddFTP: ["Add_FTP"],
    UpdateFTP: ["Update_FTP"],
    DeleteFTP: ["Delete_FTP"],
    UpdateFTPStatus: ["Update_FTP"],
    AddAbby: ["Add_Abby"],
    UpdateAbby: ["Update_Abby"],
    DeleteAbby: ["Delete_Abby"],
    UpdateAbbyStatus: ["Update_Abby"],
    AddTextTranslation: ["Add_Text_Translation"],
    UpdateTextTranslation: ["Update_Text_Translation"],
    DeleteTextTranslation: ["Delete_Text_Translation"],
    UpdateTextTranslationStatus: ["Update_Text_Translation"],
    AddFaxIntegration: ["Add_Fax_Integration"],
    UpdateFaxIntegration: ["Update_Fax_Integration"],
    DeleteFaxIntegration: ["Delete_Fax_Integration"],
    UpdateFaxIntegrationStatus: ["Update_Fax_Integration"],
    AddNetwork: ["Add_Network"],
    UpdateNetwork: ["Update_Network"],
    DeleteNetwork: ["Delete_Network"],
    NetworkStatus: ["Update_Network"],
    AddAudio: ["Add_Audio"],
    UpdateAudio: ["Update_Audio"],
    DeleteAudio: ["Delete_Audio"],
    UpdateAudioStatus: ["Update_Audio"],
  },
};

/**
 * Either This apis are being used by admin only or not being used anywhere
 */
const adminDomainRestrictedAPIs = {
  mutation: [
    "ChangePassword",
    "AddArea",
    "UpdateArea",
    "AreaDeleted",
    "AreaStatus",
    "ApprovedSignup",
    "CustomizationDeleted",
    "AddCustomizationText",
    "CustomizationTextDeleted",
    "CustomizationTextStatus",
    "JobListDeleted",
    "LicenseDeleted",
    "AddLogging",
    "UpdateLogging",
    "LoggingDeleted",
    "LoggingStatus",
    "UpdatePartner",
    "ProcessPayment",
    "AddPermission",
    "AddPublicUpload",
    "AddSetting",
    "UpdateSetting",
    "SettingDeleted",
    "SettingStatus",
    "AddValidator",
    "UpdateValidator",
    "ValidatorDeleted",
    "ValidatorStatus",
  ],
  query: [
    "GetAreas",
    "GetArea",
    "GetInternalAuthProvider",
    "GetCustomPermission",
    "GetUsage",
    "GetThingCertificates",
    "GetSettings",
    "GetSetting",
    "GetLoggings",
    "GetLogging",
    "GetCustomizationTexts",
    "GetCustomerLevelPermission",
    "GetRootLevelPermission",
    "GetParentPermission",
    "GetChildPermission",
    "GetJobList",
    "GetJobListByCustomerID",
    "GetPartner",
    "GetLanguages",
    "GetValidators",
    "GetValidator",
    "GetLocationsByCustomerID",
  ],
};

/**
 * These apis are public
 */
const publicAPIs = {
  mutation: ["GenerateEmailForLocation"],
  query: ["GetUser", "ImportThing", "ImportDevice", "ImportLocation", "ImportAccount"]
}

/**
 * These apis are being used by kiosk or embeded
 */
const apiUsedByKiosk = {
  mutation: [
    "AddUsage",
    "ValidateCardNumber",
    "ValidateCardNumberPin",
    "EmailService",
    "SignedUrl",
    "UploadMultipleFiles",
    "UploadMultipleFilesV2",
    "ConfirmFileUpload",
    "SaveIppPrinterAttributes",
    "AddFax",
    "UpdateFax",
    "FaxDeleted",
    "FaxStatus",
    "SendSrFaxRequest",
    "IppJobStatus",
    "ProcessPayment",
    "AddAuditLogs",
    "GetPaymentConfiguration",
    "DeleteFile",
    "GetNayaxCheckout",
    "SendAtriumTransaction",
    "GetAtriumBalance",
    "GetBalance",
    "SendTransaction"
  ],
  query: ["GetFaxes", "GetFax"],
};

module.exports = {
  permissionMapping,
  adminDomainRestrictedAPIs,
  publicAPIs,
  apiUsedByKiosk
};
