
module.exports = {
  usageData: [
    { label: 'Customer', value: 'Customer' },
    { label: 'TransactionDate', value: 'TransactionDate' },
    { label: 'TransactionStartTime', value: 'TransactionStartTime' },
    { label: 'TransactionEndTime', value: 'TransactionEndTime' },
    { label: 'Location', value: 'Location' },
    { label: 'Thing', value: 'Thing' },
    { label: 'UserType', value: 'UserType' },
    { label: 'JobDeliveryMethod', value: 'Print.JobDeliveryMethod' },
    { label: 'PrintJobSubmitted', value: 'Print.PrintJobSubmitted' },
    { label: 'Device', value: 'Print.Device' },
    { label: 'TotalCost', value: 'Print.TotalCost' },
    { label: 'GrayscaleCost', value: 'Print.GrayscaleCost' },
    { label: 'ColorCost', value: 'Print.ColorCost' },
    { label: 'TotalPages', value: 'Print.TotalPages' },
    { label: 'GrayscalePages', value: 'Print.GrayscalePages' },
    { label: 'ColorPages', value: 'Print.ColorPages' },
    { label: 'Copies', value: 'Print.Copies' },
    { label: 'PaperSize', value: 'Print.PaperSize' },
    { label: 'DocumentSize', value: 'Print.DocumentSize' },
    { label: 'Duplex', value: 'Print.Duplex' },
    { label: 'ColorType', value: 'Print.ColorType' },
    { label: 'JobPrinted', value: 'Print.JobPrinted' },
    { label: 'JobPrintedBy', value: 'Print.JobPrintedBy' },
    { label: 'JobPrintedFrom', value: 'Print.JobPrintedFrom' },
    { label: 'PrintCancelled', value: 'Print.PrintCancelled' },
    { label: 'ReasonCancelled', value: 'ReasonCancelled' },
    { label: 'JobType', value: 'Print.JobType' },
    { label: 'ReleaseCode', value: 'Print.ReleaseCode' },
    { label: 'PaymentType', value: 'Print.PaymentType' },
    { label: 'DocumentName', value: 'Print.DocumentName' },
    { label: 'DocumentType', value: 'Print.DocumentType' },
    { label: 'Orientation', value: 'Print.Orientation' },
    { label: 'Staple', value: 'Print.Staple' },
    { label: 'BillingAccountId', value: 'BillingAccountId' },
    { label: 'BillingAccountName', value: 'BillingAccountName' },
    { label: 'CurrencyCode', value: 'CurrencyCode' }
  ],
  licenseMapping: [
    { label: 'Customer Name', value: 'CustomerName' },
    { label: 'Customer Type', value: 'CustomerType' },
    { label: 'Tier', value: 'Tier' },
    { label: 'Partner', value: 'Partner' },
    { label: 'Expiry Date', value: 'RegisteredTo' },
    { label: 'Devices', value: 'Devices' },
    { label: 'Things', value: 'Things' },
    { label: 'Envision ware', value: 'Envisionware' },
    { label: 'ItsMyPc', value: 'ItsMyPc' },
  ],
  thingData: [
    { label: 'Display', value: 'Display' },
    { label: 'Thing', value: 'Thing' },
    { label: 'ThingType', value: 'ThingType' },
    { label: 'LocationName', value: 'LocationName' },
    { label: 'DeviceName', value: 'DeviceName' },
    { label: 'AutoSelectPrinter', value: 'AutoSelectPrinter' },
    { label: 'GuestCopy', value: 'GuestCopy' },
    { label: 'GuestScan', value: 'GuestScan' },
    { label: 'PrintUSBAsGuest', value: 'PrintUSBAsGuest' },
    { label: 'PrintUSBWithAccount', value: 'PrintUSBWithAccount' },
    { label: 'DebugLog', value: 'DebugLog' },
    { label: 'ClearLogsAfter', value: 'ClearLogsAfter' },
    { label: 'TimeOut', value: 'TimeOut' },
    { label: 'PromptForAccount', value: 'PromptForAccount' },
    { label: 'LoginOptionReleaseCode', value: 'LoginOptionReleaseCode'},
    { label: 'LoginOptionReleaseCodeLabel', value: 'LoginOptionReleaseCodeLabel'},
    { label: 'LoginOptionReleaseCodeHomeMessage', value: 'LoginOptionReleaseCodeHomeMessage'},
    { label: 'LoginOptionGuestName', value: 'LoginOptionGuestName'},
    { label: 'LoginOptionGuestLabel', value: 'LoginOptionGuestLabel'},
    { label: 'AutomaticSoftwareUpdate', value: 'AutomaticSoftwareUpdate'},
    { label: 'LoginOptionCardNumber', value: 'LoginOptionCardNumber'},
    { label: 'LoginOptionCardNumberPin', value: 'LoginOptionCardNumberPin'},
    { label: 'ExternalCardValidation', value: 'ExternalCardValidation'},
    { label: 'ExternalCardIdpName', value: 'ExternalCardIdpName'},
    { label: 'LoginOptionUsername', value: 'LoginOptionUsername'},
    { label: 'LoginOptionUsernameLabel', value: 'LoginOptionUsernameLabel'},
    { label: 'LoginOptionIdentityProvider', value: 'LoginOptionIdentityProvider'},
    { label: 'LoginOptionIdentityProviderOne', value: 'LoginOptionIdentityProviderOne'},
    { label: 'LoginOptionIdentityProviderTwo', value: 'LoginOptionIdentityProviderTwo'},
    { label: 'LoginOptionIdentityProviderThree', value: 'LoginOptionIdentityProviderThree'},
    { label: 'LoginOptionIdentityProviderFour', value: 'LoginOptionIdentityProviderFour'},
    { label: 'Tags', value: 'Tags' },
    { label: 'DisplayQrCode', value: 'DisplayQrCode' },
  ],
  deviceData: [
    { label: 'Device', value: 'Device' },
    { label: 'DeviceType', value: 'DeviceType' },
    { label: 'Description', value: 'Description' },
    { label: 'LocationName', value: 'LocationName' },
    { label: 'ThingName', value: 'ThingName' },
    { label: 'MacAddress', value: 'MacAddress' },
    { label: 'Tags', value: 'Tags' },
  ],
  locationData: [
    { label: 'Location', value: 'Location' },
    { label: 'Description', value: 'Description' },
    { label: 'Address', value: 'Address' },
    { label: 'City', value: 'City' },
    { label: 'State', value: 'State' },
    { label: 'Country', value: 'Country' },
    { label: 'ZipCode', value: 'ZipCode' },
    { label: 'OpenHoursOne', value: 'OpenHoursOne' },
    { label: 'ClosingHoursOne', value: 'ClosingHoursOne' },
    { label: 'DayOne', value: 'DayOne' },
    { label: 'OpenHoursTwo', value: 'OpenHoursTwo' },
    { label: 'ClosingHoursTwo', value: 'ClosingHoursTwo' },
    { label: 'DayTwo', value: 'DayTwo' },
    { label: 'OpenHoursThree', value: 'OpenHoursThree' },
    { label: 'ClosingHoursThree', value: 'ClosingHoursThree' },
    { label: 'DayThree', value: 'DayThree' },
    { label: 'OpenHoursFour', value: 'OpenHoursFour' },
    { label: 'ClosingHoursFour', value: 'ClosingHoursFour' },
    { label: 'DayFour', value: 'DayFour' },
    { label: 'OpenHoursFive', value: 'OpenHoursFive' },
    { label: 'ClosingHoursFive', value: 'ClosingHoursFive' },
    { label: 'DayFive', value: 'DayFive' },
    { label: 'OpenHoursSix', value: 'OpenHoursSix' },
    { label: 'ClosingHoursSix', value: 'ClosingHoursSix' },
    { label: 'DaySix', value: 'DaySix' },
    { label: 'OpenHoursSeven', value: 'OpenHoursSeven' },
    { label: 'ClosingHoursSeven', value: 'ClosingHoursSeven' },
    { label: 'DaySeven', value: 'DaySeven' },
    { label: 'CurrencyCode', value: 'CurrencyCode' },
    { label: 'Tags', value: 'Tags' },
    { label: 'Searchable', value: 'Searchable' }
  ],
  accountData: [
    { label: 'AccountId', value: 'AccountId' },
    { label: 'AccountName', value: 'AccountName' },
    { label: 'Description', value: 'Description' },
    { label: 'Tags', value: 'Tags' },
  ]
}